development:
  adapter: postgresql
  encoding: utf8
  database: bizworld_development
  pool: 5

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: bizworld_test
  pool: 5

production:
  adapter: postgresql
  encoding: utf8
  database: bizworld_production
  pool: 5
